
services:
  api:
    build:
      context: ./PermisosPuestosApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=172.29.99.8;Database=PERFILES_BD;User Id=fsalazarmo;Password=3i5q32sNpf8B;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Jwt__Key=SuperSecretKeyForJWTAuthProyectoPermisosXPuesto2024+
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
