server {
    # El servidor escucha en el puerto 8080 porque los puertos menores a 1024 requieren permisos root.
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Enrutamiento para SPA de Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}
